http:
  routers:
    api:
      rule: "Host(`api.localhost`) || PathPrefix(`/api`)"
      entryPoints: [web]
      service: api
      middlewares: [api-strip]

  middlewares:
    api-strip:
      stripPrefix:
        prefixes: ["/api"]
        forceSlash: true

  services:
    api:
      loadBalancer:
        servers:
          - url: "http://api:3000"
