http:
  routers:
    api:
      rule: "Host(`api-demo.yoke-th.me`)"
      entryPoints: [websecure]
      service: api
      middlewares: [api-strip]
      tls: {}

  middlewares:
    api-strip:
      stripPrefix:
        prefixes: ["/api"]
        forceSlash: true

  services:
    api:
      loadBalancer:
        servers:
          - url: "http://api:3000"
